name: CI/CD Pipeline

on:
  pull_request:
    branches: [ master ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Клонируем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest ruff

      # 4. Запускаем тесты
      - name: Run Unit Tests
        run: |
          python -m pytest tests/ -v

      # 5. Запускаем Ruff линтинг
      - name: Run Ruff Linting
        run: |
          ruff check --output-format=github .
